# Generated by Django 5.2.5 on 2025-09-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_chatenquiry_delete_homecontact_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatenquiry',
            name='created_at',
        ),
    ]
