# Generated by Django 5.2.5 on 2025-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_remove_chatenquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
