# Generated by Django 5.2 on 2025-09-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=160)),
                ('meta_description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('main_heading', models.CharField(max_length=255)),
                ('intro_descrption', models.TextField()),
                ('product_video_link', models.URLField(blank=True, help_text='add video link here', null=True)),
                ('cta_video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='videos')),
                ('product_image_alt', models.CharField(blank=True, null=True)),
                ('precision_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('precision_description', models.TextField(blank=True, null=True)),
                ('why_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('why_description', models.TextField(blank=True, null=True)),
                ('commitment_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('commitment_description', models.TextField(blank=True, null=True)),
                ('sub_product_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_product_description', models.TextField(blank=True, null=True)),
                ('cta_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitmentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(help_text='Add commiments')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_points', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(help_text='Add Benefite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advantage', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub-product-image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='products.product')),
            ],
        ),
    ]
