# Generated by Django 5.2 on 2025-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical',
            field=models.CharField(default='https://acedigitaldentallaboratory.com/product/', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='h1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
