# Generated by Django 5.2 on 2025-09-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_canonical_product_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precision_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precision_heading',
        ),
    ]
