# Generated by Django 5.2 on 2025-09-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_precision_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='title',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
