# Generated by Django 5.2 on 2025-09-02 08:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_advantage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=180, null=True)),
                ('slug', models.SlugField()),
                ('meta_description', models.TextField(unique=True)),
                ('canonical', models.CharField(default='https://acedigitaldentallaboratory.com/blog/', max_length=180)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-image')),
                ('alt', models.CharField(blank=True, max_length=180, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
