# Generated by Django 5.2.5 on 2025-09-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_author_blogs_schema_blogs_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=180, null=True)),
                ('meta_description', models.TextField()),
                ('breadcrumb', models.CharField(blank=True, max_length=100, null=True)),
                ('canonical', models.CharField(default='https://acedigitaldentallaboratory.com/category/', max_length=180)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='SEO')),
                ('alt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.blogcategory'),
        ),
    ]
