# Generated by Django 5.2.5 on 2025-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_blogcategory_product_schema_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='alt',
            field=models.CharField(blank=True, null=True),
        ),
    ]
