# Generated by Django 5.2.5 on 2025-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cta_btn_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
