# Generated by Django 5.2.5 on 2025-09-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_cta_btn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentpoint',
            name='point_image',
            field=models.ImageField(blank=True, null=True, upload_to='commitment'),
        ),
    ]
