# Generated by Django 5.2.5 on 2025-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_commitmentpoint_point_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentpoint',
            name='point_image',
            field=models.FileField(blank=True, help_text='upload your image here', null=True, upload_to='commitment'),
        ),
    ]
